name: "Build multi-arch image"

on:
  push:
    branches:
      - 'master'
    tags:
      - '**'

jobs:
  tag:
    name: Extract tag name
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.tag.outputs.result }}
    steps:
      - name: Extract the tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref === "refs/heads/master"
              ? 'latest'
              : context.payload.ref.replace(/^refs\/(tags|heads)\//, '');

  build:
    needs:
      - tag
    name: Build
    uses: pyldin601/build-multiarch-on-aws-spots/.github/workflows/build-multiarch-on-aws-spots.yml@5c448cb91b65e617237df2326723441f25f8eea0
    with:
      DOCKER_IMAGE_TAG: ${{ needs.tag.outputs.TAG }}
      DOCKER_IMAGE_NAME: "mwader/static-ffmpeg"
      WORKFLOW_CHECKOUT: 5c448cb91b65e617237df2326723441f25f8eea0
      AWS_REGION: eu-central-1
      AWS_EC2_INSTANCE_SIZE: xlarge
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
